import type { NextPage } from "next";
import Head from "next/head";
import Router from "next/router";
import styled from "styled-components";

const SBody = styled.div`
  display: flex;
  justify-content: center;
`;

const SMain = styled.div`
  width: 100%;
  display: flex;
  flex-direction: column;
  max-width: 65rem;
  margin: 1rem;
  margin-top: 1.5rem;
`;

const SPageHeader = styled.p`
  font-weight: 500;
  font-size: 1.5rem;
  line-height: 1.5rem;
`;

const SCreateQuiz = styled.div`
  width: 15rem;
  height: 3.5rem;
  cursor: pointer;
  padding: 1.25rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin: 2.5rem 0 4rem 0;

  background: linear-gradient(#fff, #fff),
    linear-gradient(141.29deg, #fca3a3 -6.98%, #dfa3fc 111.45%);
  background-origin: padding-box, border-box;
  background-repeat: no-repeat;
  border: 2px solid transparent;
  border-radius: 1em;
`;

const Sp = styled.p`
  font-weight: 600;
  font-size: 2rem;
  line-height: 2rem;
  margin-bottom: 2rem;
`;

const SQuizCard = styled.div`
  display: flex;
  width: 13rem;
  height: 14.5rem;
  cursor: pointer;
  padding: 20px 10px;
  background-color: #3e9fff;
  flex-direction: column;
  justify-content: end;
  border-radius: 1rem;
`;

const SQuizCardBox = styled.div`
  display: grid;
  padding-bottom: 1rem;
  gap: 5rem;
  grid-template-columns: repeat(auto-fit, minmax(12rem, 12rem));
`;

const SQuizDetails = styled.p`
  font-weight: 600;
  font-size: 1rem;
  line-height: 1rem;
  color: #fff;
  padding-bottom: 10px;
`;

const SQuizDuration = styled.p`
  font-size: 0.8rem;
  line-height: 0.8rem;
  color: #fff;
`;


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SBody>
        <SMain>
          <SPageHeader>QuestZen</SPageHeader>
          <SCreateQuiz onClick={() => Router.push("./set-questions")}>
            <p>Create a Quiz</p>
            <img src="addLight.svg" alt="" />
          </SCreateQuiz>

          <Sp>Live Quiz</Sp>
          <SQuizCardBox>
            <SQuizCard>
              <SQuizDetails>AlgoReach Quiz</SQuizDetails>
              <SQuizDetails style={{ fontWeight: "400" }}>
                Curator: Kelvin Praise
              </SQuizDetails>
              <SQuizDuration>Duration: 3days</SQuizDuration>
            </SQuizCard>
            <SQuizCard>
              <SQuizDetails>AlgoReach Quiz</SQuizDetails>
              <SQuizDetails style={{ fontWeight: "400" }}>
                Curator: Kelvin Praise
              </SQuizDetails>
              <SQuizDuration>Duration: 3days</SQuizDuration>
            </SQuizCard>
            <SQuizCard>
              <SQuizDetails>AlgoReach Quiz</SQuizDetails>
              <SQuizDetails style={{ fontWeight: "400" }}>
                Curator: Kelvin Praise
              </SQuizDetails>
              <SQuizDuration>Duration: 3days</SQuizDuration>
            </SQuizCard>
            <SQuizCard>
              <SQuizDetails>AlgoReach Quiz</SQuizDetails>
              <SQuizDetails style={{ fontWeight: "400" }}>
                Curator: Kelvin Praise
              </SQuizDetails>
              <SQuizDuration>Duration: 3days</SQuizDuration>
            </SQuizCard>
            <SQuizCard>
              <SQuizDetails>AlgoReach Quiz</SQuizDetails>
              <SQuizDetails style={{ fontWeight: "400" }}>
                Curator: Kelvin Praise
              </SQuizDetails>
              <SQuizDuration>Duration: 3days</SQuizDuration>
            </SQuizCard>
          </SQuizCardBox>
        </SMain>
      </SBody>
    </>
  );
};

export default Home;
